[build]
publish = "public"
command = "git submodule update -f --init && npm install && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
